### ISSUE TITLE
error when running quickstart.sh

### ISSUE THREAD

**Issue by djrbeen** [bavc/signalserver#301]
Hi,
Thank you for share your great work!
I'm having this error when run quickstart.sh

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/src/app/signalserver/__init__.py", line 5, in <module>
    from .celery import app as celery_app  # noqa
  File "/usr/src/app/signalserver/celery.py", line 14, in <module>
    broker='amqp://guest@rmq:5672//')
  File "/usr/local/lib/python3.4/site-packages/celery/app/base.py", line 286, in __init__
    self._fixups = [symbol_by_name(fixup)(self) for fixup in self.fixups]
  File "/usr/local/lib/python3.4/site-packages/celery/app/base.py", line 286, in <listcomp>
    self._fixups = [symbol_by_name(fixup)(self) for fixup in self.fixups]
  File "/usr/local/lib/python3.4/site-packages/celery/fixups/django.py", line 46, in fixup
    _verify_django_version(django)
  File "/usr/local/lib/python3.4/site-packages/celery/fixups/django.py", line 34, in _verify_django_version
    raise ImproperlyConfigured('Celery 4.x requires Django 1.11 or later.')
celery.exceptions.ImproperlyConfigured: Celery 4.x requires Django 1.11 or later` 

What can I do to fix this issue?
Thanks in advance, Best!

Djrbeen

**Comment by djrbeen** [comment]
This is the docker that starts over and over when crashes with the celery error
`CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                      NAMES
089595657f6f        signalserver_web    "python manage.py mi…"   8 minutes ago       Exited (1) 7 minutes ago                               signalserver_web_run_24`

**Comment by dericed** [comment]
Hi @djrbeen. Thanks for your issue. Signalserver hasn't been under development for a few years and personally I haven't run it since the project was active. I am working actively on QCTools though. Nudging @iamdamosuzuki as it may make sense to update the project to say it's not currently active, though I'd be very interested in a new maintainer volunteered.
